export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as InfoSection } from "./InfoSection/InfoSection";
export { default as InfoSection2 } from "./InfoSection/InfoSection2";
export { default as InfoSection3 } from "./InfoSection/InfoSection3";
export { default as InfoSection4 } from "./InfoSection/InfoSection4";
export { default as ServiceSection } from "./InfoSection/ServiceSection";
export { default as Pricing } from "./Pricing/Pricing";
export { default as JoinsUs } from "./InfoSection/JoinUs";
